// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

// Export a plain `any` config object so Next.js TypeScript checks don't
// complain about the internal Prisma config types during the app build.
// Prisma will still be able to load this file at runtime.
const config: any = {
  schema: { kind: "single", filePath: "prisma/schema.prisma" },
  datasource: {
    url: process.env.DATABASE_URL,
  },
};

export default config;
