// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "@prisma/config";

// Use defineConfig from @prisma/config but directly read the env var from
// process.env to avoid relying on the `env()` helper which may differ
// between Prisma versions.
export default defineConfig({
  // Use the `single` shape that the `@prisma/config` parser expects.
  schema: { kind: "single", filePath: "prisma/schema.prisma" },
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
